---
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  regenerate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt --user
      - name: Regenerate csv data
        run: python generate_data.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
