---
on:
  pull_request:
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-pip-requirements
      - run: pylint *.py
      - run: pytest test_*.py
