---
on:
  pull_request:
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt --user
      - run: pylint *.py
      - run: pytest test_*.py
